baseURL = 'https://sophia.seiya-world.com'
languageCode = 'en-us'
title = 'Seiya World'
theme = 'hugo-theme-relearn'

[params]
ordersectionsby = "title"

collapsibleMenu = true
themeVariant = "neon"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true